{{/*
Common helpers : naming, labels, image refs, postgres password resolution.
*/}}

{{- define "rhorizon.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "rhorizon.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- define "rhorizon.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "rhorizon.labels" -}}
helm.sh/chart: {{ include "rhorizon.chart" . }}
app.kubernetes.io/name: {{ include "rhorizon.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.commonLabels }}
{{ toYaml . }}
{{- end }}
{{- end -}}

{{- define "rhorizon.selectorLabels" -}}
app.kubernetes.io/name: {{ include "rhorizon.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}

{{/* Service account name */}}
{{- define "rhorizon.serviceAccountName" -}}
{{- if .Values.serviceAccount.create -}}
{{ default (include "rhorizon.fullname" .) .Values.serviceAccount.name }}
{{- else -}}
{{ default "default" .Values.serviceAccount.name }}
{{- end -}}
{{- end -}}

{{/* Image refs (tag fallback to AppVersion) */}}
{{- define "rhorizon.image.api" -}}
{{- $tag := .Values.image.api.tag | default .Chart.AppVersion -}}
{{ printf "%s:%s" .Values.image.api.repository $tag }}
{{- end -}}

{{- define "rhorizon.image.frontend" -}}
{{- $tag := .Values.image.frontend.tag | default .Chart.AppVersion -}}
{{ printf "%s:%s" .Values.image.frontend.repository $tag }}
{{- end -}}

{{- define "rhorizon.image.postgres" -}}
{{ printf "%s:%s" .Values.image.postgres.repository .Values.image.postgres.tag }}
{{- end -}}

{{/*
PostgreSQL password Secret name. Either externally-provided
(values.postgres.external.existingSecret) or generated by us.
*/}}
{{- define "rhorizon.postgres.secretName" -}}
{{- if and .Values.postgres.external.enabled .Values.postgres.external.existingSecret -}}
{{ .Values.postgres.external.existingSecret }}
{{- else -}}
{{ printf "%s-postgres" (include "rhorizon.fullname" .) }}
{{- end -}}
{{- end -}}

{{/* PG host : in-cluster service or external endpoint. */}}
{{- define "rhorizon.postgres.host" -}}
{{- if .Values.postgres.external.enabled -}}
{{ .Values.postgres.external.host }}
{{- else -}}
{{ printf "%s-postgres" (include "rhorizon.fullname" .) }}
{{- end -}}
{{- end -}}

{{- define "rhorizon.postgres.database" -}}
{{- if .Values.postgres.external.enabled -}}
{{ .Values.postgres.external.database | default "rhorizon" }}
{{- else -}}
rhorizon
{{- end -}}
{{- end -}}

{{- define "rhorizon.postgres.username" -}}
{{- if .Values.postgres.external.enabled -}}
{{ .Values.postgres.external.username | default "rhorizon" }}
{{- else -}}
rhorizon
{{- end -}}
{{- end -}}

{{- define "rhorizon.postgres.port" -}}
{{- if .Values.postgres.external.enabled -}}
{{ .Values.postgres.external.port | default 5432 }}
{{- else -}}
5432
{{- end -}}
{{- end -}}
