apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-api-headless" (include "rhorizon.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rhorizon.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      name: http
  selector:
    {{- include "rhorizon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
