apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-frontend" (include "rhorizon.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rhorizon.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "rhorizon.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "rhorizon.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      serviceAccountName: {{ include "rhorizon.serviceAccountName" . }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: {{ include "rhorizon.image.frontend" . }}
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: 8200
              name: http
          env:
            - name: TLS_ENABLED
              value: "false"
            - name: API_UPSTREAM
              value: "{{ printf "%s-api" (include "rhorizon.fullname" .) }}:{{ .Values.service.api.port }}"
          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.frontend.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /run
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: nginx-cache
          emptyDir:
            medium: Memory
            sizeLimit: 8Mi
        - name: nginx-run
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: nginx-conf
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
