#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2024-2026 shdw <contact@resurgamus.com>
#
# One-shot setup for the rhorizon vault connector (Claude Code / Claude Desktop
# / Codex / opencode). Mints a DEDICATED READ-ONLY vault token, writes a
# fail-closed policy, registers the MCP server with local clients when their
# CLIs are present, and prints the opencode block. Idempotent-ish: re-running
# revokes+remints the token.
#
# Prereqs:
#   - rhorizon-mcp-server on PATH (pip/pipx install rhorizon-mcp) OR set
#     RHORIZON_MCP_BIN to its absolute path (e.g. a venv binary).
#   - An admin vault token with tokens:rw covering the target namespaces,
#     via RHORIZON_ADMIN_TOKEN or RHORIZON_ADMIN_TOKEN_FILE.
#
# Usage:
#   RHORIZON_ADMIN_TOKEN_FILE=~/.config/rhorizon/admin.token \
#     ./setup.sh --namespaces mcp,forgejo [--vault http://127.0.0.1:8200]
set -euo pipefail

VAULT_URL="${RHORIZON_VAULT_URL:-http://127.0.0.1:8200}"
NAMESPACES="${RHORIZON_NAMESPACES:-}"
TOKEN_NAME="${RHORIZON_MCP_TOKEN_NAME:-mcp-agent}"
TOKEN_FILE="${RH_TOKEN_FILE:-$HOME/.config/rhorizon/mcp.token}"
POLICY_FILE="${RHORIZON_MCP_POLICY:-$HOME/.config/rhorizon-mcp/policy.toml}"

while [ $# -gt 0 ]; do
  case "$1" in
    --namespaces) NAMESPACES="$2"; shift 2 ;;
    --vault)      VAULT_URL="$2";  shift 2 ;;
    --name)       TOKEN_NAME="$2"; shift 2 ;;
    -h|--help)    grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done
[ -n "$NAMESPACES" ] || { echo "error: --namespaces required (comma-separated, e.g. mcp,forgejo)" >&2; exit 2; }

# ---- resolve the MCP server binary ----------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BIN="${RHORIZON_MCP_BIN:-$(command -v rhorizon-mcp-server || true)}"
SERVER_DIR="$(cd "$SCRIPT_DIR" 2>/dev/null && pwd || true)"
if [ -z "$BIN" ] && [ -n "$SERVER_DIR" ] && [ -f "$SERVER_DIR/pyproject.toml" ] && command -v pipx >/dev/null 2>&1; then
  echo ">> rhorizon-mcp-server not found; installing the bundled server via pipx..."
  pipx install "$SERVER_DIR" >/dev/null 2>&1 || true
  BIN="$(command -v rhorizon-mcp-server || true)"
fi
[ -n "$BIN" ] || { echo "error: rhorizon-mcp-server not found. Install the bundled server ('pipx install "$SCRIPT_DIR"') or set RHORIZON_MCP_BIN." >&2; exit 1; }

# ---- resolve the admin token (never printed) ------------------------------
ADMIN=""
if [ -n "${RHORIZON_ADMIN_TOKEN:-}" ]; then ADMIN="$RHORIZON_ADMIN_TOKEN"
elif [ -n "${RHORIZON_ADMIN_TOKEN_FILE:-}" ] && [ -r "$RHORIZON_ADMIN_TOKEN_FILE" ]; then ADMIN="$(cat "$RHORIZON_ADMIN_TOKEN_FILE")"
else echo "error: provide an admin token (tokens:rw) via RHORIZON_ADMIN_TOKEN or RHORIZON_ADMIN_TOKEN_FILE." >&2; exit 1; fi

# JSON array of namespaces from the comma list
NS_JSON="$(printf '%s' "$NAMESPACES" | awk -F, '{for(i=1;i<=NF;i++){printf (i>1?",":"") "\"" $i "\""}}')"

echo ">> revoking any existing active token named '$TOKEN_NAME'..."
OLD_ID="$(curl -sS -m 5 -H "Authorization: Bearer $ADMIN" "$VAULT_URL/api/v1/vault/tokens/" \
  | python3 -c "import sys,json;d=json.load(sys.stdin);items=d if isinstance(d,list) else d.get('tokens',d.get('items',[]));print(next((t['id'] for t in items if t.get('name')=='$TOKEN_NAME' and t.get('active',True)),''))" 2>/dev/null || true)"
[ -n "$OLD_ID" ] && curl -sS -m 5 -o /dev/null -X DELETE -H "Authorization: Bearer $ADMIN" "$VAULT_URL/api/v1/vault/tokens/$OLD_ID" || true

echo ">> minting read-only token '$TOKEN_NAME' (secrets:r on: $NAMESPACES)..."
# NOTE: no allowed_ips -- a rootless podman/containerized vault sees the
# slirp/pasta gateway (not 127.0.0.1) as the source, so an IP lock would 403.
mkdir -p "$(dirname "$TOKEN_FILE")"
curl -sS -m 8 -X POST -H "Authorization: Bearer $ADMIN" -H "Content-Type: application/json" \
  "$VAULT_URL/api/v1/vault/tokens/" \
  -d "{\"name\":\"$TOKEN_NAME\",\"permissions\":{\"secrets\":\"r\",\"namespaces\":[$NS_JSON]}}" \
  | python3 -c "import sys,json;d=json.load(sys.stdin);t=d.get('token')
open('$TOKEN_FILE','w').write(t) if t else (sys.stderr.write('mint failed: '+json.dumps(d)[:300]+'\n') or sys.exit(1))"
chmod 600 "$TOKEN_FILE"
echo "   token -> $TOKEN_FILE (0600)"

echo ">> writing fail-closed policy -> $POLICY_FILE"
mkdir -p "$(dirname "$POLICY_FILE")"
{
  echo "# Auto-generated by rhorizon-mcp/setup.sh. Fail-closed."
  echo "[secrets]"; echo "whitelist = []"
  echo "[namespaces]"; printf 'allow = [%s]\n' "$NS_JSON"
  echo "[tools]"
  echo 'allow = ["vault_status","vault_whoami","vault_list_namespaces","vault_list_secrets","vault_get_secret"]'
} > "$POLICY_FILE"
chmod 600 "$POLICY_FILE"

# ---- register with Claude Code (if the CLI is present) --------------------
if command -v claude >/dev/null 2>&1; then
  echo ">> registering MCP server 'rhorizon-vault' with Claude Code (user scope)..."
  claude mcp remove rhorizon-vault >/dev/null 2>&1 || true
  claude mcp add rhorizon-vault --scope user \
    -e "RH_VAULT_URL=$VAULT_URL" \
    -e "RH_TOKEN_FILE=$TOKEN_FILE" \
    -e "RHORIZON_MCP_POLICY=$POLICY_FILE" \
    -- "$BIN"
  claude mcp list 2>/dev/null | grep -i rhorizon-vault || true
else
  echo ">> 'claude' CLI not found -- copy mcp/claude.mcp.json to your project root as .mcp.json"
fi

# ---- register with Codex (if the CLI is present) --------------------------
if command -v codex >/dev/null 2>&1; then
  echo ">> registering MCP server 'rhorizon-vault' with Codex (global config)..."
  codex mcp remove rhorizon-vault >/dev/null 2>&1 || true
  codex mcp add rhorizon-vault \
    --env "RH_VAULT_URL=$VAULT_URL" \
    --env "RH_TOKEN_FILE=$TOKEN_FILE" \
    --env "RHORIZON_MCP_POLICY=$POLICY_FILE" \
    -- "$BIN"
  codex mcp list 2>/dev/null | grep -i rhorizon-vault || true
else
  echo ">> 'codex' CLI not found -- merge mcp/codex.config.toml into ~/.codex/config.toml"
fi

# ---- opencode block, ready to paste ---------------------------------------
cat <<EOF

>> opencode: merge this "mcp" block into ~/.config/opencode/opencode.json
{
  "mcp": {
    "rhorizon-vault": {
      "type": "local",
      "command": ["$BIN"],
      "environment": {
        "RH_VAULT_URL": "$VAULT_URL",
        "RH_TOKEN_FILE": "$TOKEN_FILE",
        "RHORIZON_MCP_POLICY": "$POLICY_FILE"
      }
    }
  }
}

Done. Restart your client; the agent gets read-only vault tools
(vault_list_secrets / vault_get_secret / ...), gated by the policy above.
EOF
